# Report on all standardized tests defined as assertion methods

PREFIX ffdq: <http://example.com/ffdq/>
PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?guid ?specification

WHERE {
    ?guid a ffdq:Specification .
    ?guid rdfs:label ?specification
}
